title: Liang Xu's Homepage
page-top-title: Liang Xu
top-section-bg-text: Urban underground space engineering
home-subtitle: Liang Xu&ensp;|&ensp;许良
copyright-text: '&copy; Liang Xu 2024-2025. All Rights Reserved.'
